[package]
name = "sdarc"
version = "0.1.1"
authors = ["qouteall"]
edition = "2024"
description = "Sharded Deferred Atomic Reference Counting"
rust-version = "1.95.0"
repository = "https://github.com/qouteall/sdarc"
readme = "README.md"
keywords = ["atomic", "arc", "reference-counting"]
categories = ["data-structures", "memory-management"]
license = "MIT OR Apache-2.0"

[dependencies]
cfg-if = "1"
crossbeam-utils = "0.8"

parking_lot = "0.12"
# to run miri, use the parking_lot from github
# parking_lot currently has no release since fixing https://github.com/Amanieu/parking_lot/issues/477
#parking_lot = { git = "https://github.com/Amanieu/parking_lot", branch = "master" }

scopeguard = "1.2"
log = "0.4"
append-only-vec = "0.1"
rustc-hash = "2.1"

membarrier2 = "0.1"
oneshot = { version = "0.2", features = ["std"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version =  "0.61", features = ["Win32_System_Threading"] }
# without the "features = ["Win32_System_Threading"]", newly created repo can compile fine,
# but if the repo has locked a different version of windows-sys then feature unification doesn't work then user will
# have compile error "cannot find `Win32` in `windows_sys`". this is a footgun.

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(miri)"] }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
arc-swap = "1"
serial_test = "4"

[[bench]]
name = "collector_bench"
harness = false
# slow, so disabled by default. run explicitly via `cargo bench --bench collector_bench`
bench = false

[[bench]]
name = "atomic_read_bench"
harness = false

[[bench]]
name = "clone_drop_contention_bench"
harness = false

[[bench]]
name = "clone_drop_single_thread_bench"
harness = false

[[bench]]
name = "shard_index_bench"
harness = false

[profile.release]
debug = true

[package.metadata.docs.rs]
# add these targets due to differnces in `curr_shard_index` implementation.
# other than `curr_shard_index`, everything is same across platforms
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
